import React from 'react';
import { 
  UploadCloud, 
  Activity, 
  Zap, 
  Library, 
  Settings, 
  Menu, 
  X,
  Play,
  Pause,
  Download,
  RefreshCw,
  Cpu,
  Music,
  Layers,
  GitBranch,
  User,
  Key,
  CreditCard,
  Sliders,
  Lock,
  ChevronRight,
  ChevronDown,
  Grid,
  List,
  Heart,
  Disc,
  Waves,
  CheckCircle,
  Loader2,
  Star,
  Folder,
  FileText,
  Trash2,
  Copy,
  Plus,
  Edit
} from 'lucide-react';

export const Icons = {
  Upload: UploadCloud,
  DNA: Activity,
  Generator: Zap,
  Library: Library,
  Settings: Settings,
  Menu: Menu,
  Close: X,
  Play: Play,
  Pause: Pause,
  Download: Download,
  Refresh: RefreshCw,
  Architecture: Cpu,
  Cpu: Cpu,
  Music: Music,
  Layers: Layers,
  Branch: GitBranch,
  User: User,
  Key: Key,
  CreditCard: CreditCard,
  Sliders: Sliders,
  Lock: Lock,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  Grid: Grid,
  List: List,
  Heart: Heart,
  Disc: Disc,
  Waves: Waves,
  CheckCircle: CheckCircle,
  Loader: Loader2,
  Star: Star,
  Folder: Folder,
  FileText: FileText,
  Trash: Trash2,
  Copy: Copy,
  Plus: Plus,
  Edit: Edit
};