import React, { useState, useRef } from 'react';
import { Info, ChevronDown, ChevronUp, X, Upload, Music } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface PromptSectionProps {
  onGenerate: () => void;
  isGenerating: boolean;
  autoGeneratedPrompt: string;
}

export function PromptSection({ onGenerate, isGenerating, autoGeneratedPrompt }: PromptSectionProps) {
  const [useAIPrompt, setUseAIPrompt] = useState(true);
  const [customPrompt, setCustomPrompt] = useState('');
  const [lyrics, setLyrics] = useState('');
  const [isInstrumental, setIsInstrumental] = useState(true);
  const [isLyricsExpanded, setIsLyricsExpanded] = useState(false);
  const [isReferenceExpanded, setIsReferenceExpanded] = useState(false);
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState('');
  const [referenceTrack, setReferenceTrack] = useState<{
    name: string;
    bpm: number;
    key: string;
    genre: string;
  } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const prompt = useAIPrompt ? autoGeneratedPrompt : customPrompt;
  const promptCharCount = prompt.length;
  const lyricsCharCount = lyrics.length;

  const suggestedTags = ['Hypnotic', 'Dark', 'Minimal', 'Driving', 'Atmospheric', 'Groovy', 'Deep', 'Raw'];

  const handleAddTag = (tag: string) => {
    if (tags.length < 10 && !tags.includes(tag) && tag.trim()) {
      setTags([...tags, tag.trim()]);
      setTagInput('');
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove));
  };

  const handleTagInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault();
      handleAddTag(tagInput);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Simulate file analysis
      setReferenceTrack({
        name: file.name,
        bpm: 126,
        key: 'A Minor',
        genre: 'Techno'
      });
    }
  };

  const handleRemoveReference = () => {
    setReferenceTrack(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="flex flex-col h-full bg-[var(--surface-charcoal)] border-r border-[var(--border-subtle)]">
      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-6">
        
        {/* Prompt Input Section */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <label className="text-white">Describe Your Track</label>
              <div className="group relative">
                <Info className="w-4 h-4 text-[#808080] cursor-help" />
                <div className="absolute left-0 top-6 w-64 p-3 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-10 text-sm text-[#808080]">
                  Describe the style, mood, instruments, or vibe you want for your track
                </div>
              </div>
            </div>

            {/* AI-Generated Toggle */}
            <div className="flex items-center gap-2">
              <span className="text-sm text-[#808080]">Use AI-Generated Prompt</span>
              <label className="relative inline-flex items-center cursor-pointer">
                <input
                  type="checkbox"
                  checked={useAIPrompt}
                  onChange={(e) => setUseAIPrompt(e.target.checked)}
                  className="sr-only peer"
                />
                <div className="w-11 h-6 bg-[#2a2a2a] peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#ff6b35]"></div>
              </label>
            </div>
          </div>

          <div className="relative">
            <textarea
              value={prompt}
              onChange={(e) => !useAIPrompt && setCustomPrompt(e.target.value)}
              readOnly={useAIPrompt}
              placeholder="e.g., Dark hypnotic techno with rolling bassline, crisp hi-hats, atmospheric pads, driving four-to-the-floor rhythm..."
              maxLength={500}
              rows={5}
              className={`w-full px-4 py-3 bg-[#0a0a0a] border border-[#2a2a2a] rounded-lg text-white placeholder-[#404040] focus:outline-none focus:border-[#ff6b35] transition-colors resize-none ${
                useAIPrompt ? 'cursor-not-allowed opacity-70' : ''
              }`}
            />
            <div className="absolute bottom-3 right-3 text-xs text-[#808080]">
              {promptCharCount} / 500
            </div>
          </div>
        </div>

        {/* Style Tags Section */}
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <label className="text-white text-sm">Style Tags</label>
            <div className="group relative">
              <Info className="w-3.5 h-3.5 text-[#808080] cursor-help" />
              <div className="absolute left-0 top-6 w-64 p-3 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-10 text-sm text-[#808080]">
                Add specific style keywords to refine your track
              </div>
            </div>
          </div>

          {/* Tag Input */}
          <input
            type="text"
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyDown={handleTagInputKeyDown}
            placeholder="Add tags... (e.g., hypnotic, dark, minimal)"
            disabled={tags.length >= 10}
            className="w-full px-4 py-2.5 bg-[#0a0a0a] border border-[#2a2a2a] rounded-lg text-white placeholder-[#404040] focus:outline-none focus:border-[#ff6b35] transition-colors text-sm"
          />

          {/* Active Tags */}
          {tags.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {tags.map((tag) => (
                <div
                  key={tag}
                  className="flex items-center gap-2 px-3 py-1.5 bg-[#ff6b35]/10 border border-[#ff6b35]/30 rounded-full text-[#ff6b35] text-sm"
                >
                  <span>{tag}</span>
                  <button
                    onClick={() => handleRemoveTag(tag)}
                    className="hover:bg-[#ff6b35]/20 rounded-full p-0.5 transition-colors"
                  >
                    <X className="w-3 h-3" />
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* Suggested Tags */}
          <div className="flex flex-wrap gap-2">
            {suggestedTags
              .filter(tag => !tags.includes(tag))
              .map((tag) => (
                <button
                  key={tag}
                  onClick={() => handleAddTag(tag)}
                  disabled={tags.length >= 10}
                  className="px-3 py-1.5 bg-[#1a1a1a] border border-[#2a2a2a] rounded-full text-[#808080] hover:text-white hover:border-[#404040] transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {tag}
                </button>
              ))}
          </div>
          {tags.length >= 10 && (
            <p className="text-xs text-[#808080]">Maximum 10 tags reached</p>
          )}
        </div>

        {/* Lyrics Section (Collapsible) */}
        <div className="space-y-3">
          <button
            onClick={() => setIsLyricsExpanded(!isLyricsExpanded)}
            className="flex items-center justify-between w-full text-left group"
          >
            <div className="flex items-center gap-2">
              <span className="text-white text-sm">Add Lyrics (Optional)</span>
              <div className="group/tooltip relative">
                <Info className="w-3.5 h-3.5 text-[#808080] cursor-help" />
                <div className="absolute left-0 top-6 w-64 p-3 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg opacity-0 invisible group-hover/tooltip:opacity-100 group-hover/tooltip:visible transition-all z-10 text-sm text-[#808080]">
                  Add lyrics for vocal tracks. Leave blank for instrumental.
                </div>
              </div>
            </div>
            {isLyricsExpanded ? (
              <ChevronUp className="w-4 h-4 text-[#808080] group-hover:text-white transition-colors" />
            ) : (
              <ChevronDown className="w-4 h-4 text-[#808080] group-hover:text-white transition-colors" />
            )}
          </button>

          <AnimatePresence>
            {isLyricsExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="space-y-3 overflow-hidden"
              >
                {/* Instrumental Checkbox */}
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id="instrumental"
                    checked={isInstrumental}
                    onChange={(e) => setIsInstrumental(e.target.checked)}
                    className="w-4 h-4 rounded border-[#2a2a2a] bg-[#0a0a0a] text-[#ff6b35] focus:ring-[#ff6b35] focus:ring-offset-0 cursor-pointer"
                  />
                  <label htmlFor="instrumental" className="text-sm text-[#808080] cursor-pointer">
                    Instrumental (no vocals)
                  </label>
                </div>

                {/* Lyrics Textarea */}
                <div className="relative">
                  <textarea
                    value={lyrics}
                    onChange={(e) => setLyrics(e.target.value)}
                    disabled={isInstrumental}
                    placeholder="Enter your lyrics here... (Verse 1, Chorus, Verse 2, etc.)"
                    maxLength={1000}
                    rows={6}
                    className={`w-full px-4 py-3 bg-[#0a0a0a] border border-[#2a2a2a] rounded-lg text-white placeholder-[#404040] focus:outline-none focus:border-[#ff6b35] transition-colors resize-none text-sm ${
                      isInstrumental ? 'cursor-not-allowed opacity-50' : ''
                    }`}
                  />
                  <div className="absolute bottom-3 right-3 text-xs text-[#808080]">
                    {lyricsCharCount} / 1000
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Reference Track Section (Collapsible) */}
        <div className="space-y-3">
          <button
            onClick={() => setIsReferenceExpanded(!isReferenceExpanded)}
            className="flex items-center justify-between w-full text-left group"
          >
            <span className="text-white text-sm">Reference Track (Optional)</span>
            {isReferenceExpanded ? (
              <ChevronUp className="w-4 h-4 text-[#808080] group-hover:text-white transition-colors" />
            ) : (
              <ChevronDown className="w-4 h-4 text-[#808080] group-hover:text-white transition-colors" />
            )}
          </button>

          <AnimatePresence>
            {isReferenceExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="space-y-3 overflow-hidden"
              >
                {!referenceTrack ? (
                  <div>
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept=".mp3,.wav,.flac"
                      onChange={handleFileUpload}
                      className="hidden"
                    />
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full px-4 py-3 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg hover:bg-[#2a2a2a] hover:border-[#404040] transition-colors flex items-center justify-center gap-2 text-[#808080] hover:text-white"
                    >
                      <Upload className="w-4 h-4" />
                      Upload Reference Track
                    </button>
                    <p className="text-xs text-[#808080] mt-2">
                      Upload a track to match its style and vibe (MP3, WAV, FLAC • Max 50MB)
                    </p>
                  </div>
                ) : (
                  <div className="p-4 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-[#ff6b35]/10 rounded flex items-center justify-center">
                          <Music className="w-5 h-5 text-[#ff6b35]" />
                        </div>
                        <div>
                          <p className="text-white text-sm">{referenceTrack.name}</p>
                          <p className="text-xs text-[#808080]">Analyzing track...</p>
                        </div>
                      </div>
                      <button
                        onClick={handleRemoveReference}
                        className="text-[#808080] hover:text-white transition-colors"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                    <div className="grid grid-cols-3 gap-3">
                      <div>
                        <p className="text-xs text-[#808080]">BPM</p>
                        <p className="text-white">{referenceTrack.bpm}</p>
                      </div>
                      <div>
                        <p className="text-xs text-[#808080]">Key</p>
                        <p className="text-white">{referenceTrack.key}</p>
                      </div>
                      <div>
                        <p className="text-xs text-[#808080]">Genre</p>
                        <p className="text-white">{referenceTrack.genre}</p>
                      </div>
                    </div>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>

      {/* Generate Button - Fixed at bottom */}
      <div className="p-6 border-t border-[var(--border-subtle)] bg-[var(--surface-charcoal)]">
        <button
          onClick={onGenerate}
          disabled={isGenerating || !prompt.trim()}
          className="w-full py-4 bg-[#ff6b35] hover:bg-[#ff8555] disabled:bg-[#2a2a2a] disabled:cursor-not-allowed text-white rounded-lg transition-colors flex items-center justify-center gap-2 text-lg font-medium"
        >
          {isGenerating ? (
            <>
              <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            'Generate Track'
          )}
        </button>
      </div>
    </div>
  );
}
